/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tfgalejandro;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.nio.charset.StandardCharsets;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.Timer;
import javax.swing.SwingUtilities;
/**
 *
 * @author alejandro
 */
public class PanelAutenticacion extends javax.swing.JPanel {

    /**
     * Creates new form PanelTraduccion
     */
    public PanelAutenticacion() {
        initComponents();
    }

    
    public void addTextoClave(String texto){
        if (texto == null) return;
        String t = texto.trim();
        if (t.isEmpty()) return;

        // Manejar tokens especiales
        if ("DEL".equalsIgnoreCase(t)) {
            deleteLast();
            return;
        }
        if ("SPACE".equalsIgnoreCase(t)) {
            String curr = new String(textoClave.getPassword());
            textoClave.setText(curr.concat(" "));
            return;
        }
        if ("NOTHING".equalsIgnoreCase(t)) {
            return; // no escribir nada
        }

        String curr = new String(textoClave.getPassword());
        textoClave.setText(curr.concat(t));
    }
    
    public void deleteLast(){
    String current = new String(textoClave.getPassword());
        if (current != null && !current.isEmpty()) {
            textoClave.setText(current.substring(0, current.length()-1));
        }
    }
    
    public void clearTextoSigno(){
        textoClave.setText("");
    }

    // Carpeta donde colocar los JSON de usuarios. Se crea si no existe.
    private static final String USERS_DIR = System.getProperty("user.dir") + File.separator + "users";
    private Color usuarioBaseBg;
    private Color claveBaseBg;

    @Override
    public void addNotify() {
        super.addNotify();
        // Guardar colores base tras crearse componentes
        usuarioBaseBg = textoUsuario.getBackground();
        claveBaseBg = textoClave.getBackground();
        // Asegurar existencia de carpeta
        try {
            File d = new File(USERS_DIR);
            if (!d.exists()) d.mkdirs();
        } catch (Exception ignored) {}

        // Bind Enter to trigger login when this panel (or its children) has focus
        this.getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT).put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "doLogin");
        this.getActionMap().put("doLogin", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                bLogin.doClick();
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTextoAleatorio = new javax.swing.JPanel();
        bLogin = new javax.swing.JButton();
        bLimpiar = new javax.swing.JButton();
        bBorrar = new javax.swing.JButton();
        panelCentral = new javax.swing.JPanel();
        textoClave = new javax.swing.JPasswordField();
        textoUsuario = new javax.swing.JTextField();
        labelUsuario = new javax.swing.JLabel();
        labelClave = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        panelTextoAleatorio.setPreferredSize(new java.awt.Dimension(100, 40));
        panelTextoAleatorio.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        bLogin.setText("Login");
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });
        panelTextoAleatorio.add(bLogin);

        bLimpiar.setText("Limpiar");
        bLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarActionPerformed(evt);
            }
        });
        panelTextoAleatorio.add(bLimpiar);

        bBorrar.setText("Borrar");
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });
        panelTextoAleatorio.add(bBorrar);

        add(panelTextoAleatorio, java.awt.BorderLayout.SOUTH);

        textoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoUsuarioActionPerformed(evt);
            }
        });

        labelUsuario.setText("Contraseña");

        labelClave.setText("Usuario");

        javax.swing.GroupLayout panelCentralLayout = new javax.swing.GroupLayout(panelCentral);
        panelCentral.setLayout(panelCentralLayout);
        panelCentralLayout.setHorizontalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentralLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCentralLayout.createSequentialGroup()
                        .addComponent(labelUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoClave, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCentralLayout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(labelClave)
                    .addContainerGap(332, Short.MAX_VALUE)))
        );
        panelCentralLayout.setVerticalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentralLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(textoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsuario)
                    .addComponent(textoClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCentralLayout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addComponent(labelClave)
                    .addContainerGap(185, Short.MAX_VALUE)))
        );

        add(panelCentral, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        deleteLast();
    }//GEN-LAST:event_bBorrarActionPerformed

    private void bLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarActionPerformed
        clearTextoSigno();
    }//GEN-LAST:event_bLimpiarActionPerformed

    private void textoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoUsuarioActionPerformed
        
    }//GEN-LAST:event_textoUsuarioActionPerformed

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        // Leer todos los JSON en USERS_DIR y buscar coincidencia user/password
        String user = textoUsuario.getText() != null ? textoUsuario.getText().trim() : "";
    String pass = "";
    try { pass = new String(textoClave.getPassword()).trim(); } catch (Exception ignored) {}
        if (user.isEmpty() || pass.isEmpty()) return;

        File dir = new File(USERS_DIR);
        if (!dir.exists() || !dir.isDirectory()) return;

        boolean matched = false;
        Pattern uPat = Pattern.compile("\"username\"\\s*:\\s*\"([^\"]+)\"", Pattern.CASE_INSENSITIVE);
        Pattern pPat = Pattern.compile("\"password\"\\s*:\\s*\"([^\"]+)\"", Pattern.CASE_INSENSITIVE);

        for (File f : dir.listFiles((d, name) -> name.toLowerCase().endsWith(".json"))) {
            try (BufferedReader br = new BufferedReader(new FileReader(f, StandardCharsets.UTF_8))) {
                StringBuilder sb = new StringBuilder();
                String line;
                while ((line = br.readLine()) != null) sb.append(line).append('\n');
                String content = sb.toString();
                Matcher mu = uPat.matcher(content);
                Matcher mp = pPat.matcher(content);
                String fu = mu.find() ? mu.group(1) : null;
                String fp = mp.find() ? mp.group(1) : null;
                if (fu != null && fp != null) {
                    if (fu.equals(user) && fp.equals(pass)) { matched = true; break; }
                }
            } catch (Exception ignore) {}
        }

        if (matched) {
            // Resaltar en verde ambos campos durante 2s y después limpiar
            SwingUtilities.invokeLater(() -> {
                textoUsuario.setBackground(Color.GREEN);
                textoClave.setBackground(Color.GREEN);
            });
            Timer t = new Timer(2000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    SwingUtilities.invokeLater(() -> {
                        textoUsuario.setBackground(usuarioBaseBg);
                        textoClave.setBackground(claveBaseBg);
                        textoUsuario.setText("");
                        textoClave.setText("");
                    });
                    ((Timer)e.getSource()).stop();
                }
            });
            t.setRepeats(false);
            t.start();
        } else {
            // Fallo: resaltar contraseña en rojo 2s y limpiar contraseña
            SwingUtilities.invokeLater(() -> textoClave.setBackground(Color.RED));
            Timer t2 = new Timer(2000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    SwingUtilities.invokeLater(() -> {
                        textoClave.setBackground(claveBaseBg);
                        textoClave.setText("");
                    });
                    ((Timer)e.getSource()).stop();
                }
            });
            t2.setRepeats(false);
            t2.start();
        }
    }//GEN-LAST:event_bLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bLimpiar;
    private javax.swing.JButton bLogin;
    private javax.swing.JLabel labelClave;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelTextoAleatorio;
    private javax.swing.JPasswordField textoClave;
    private javax.swing.JTextField textoUsuario;
    // End of variables declaration//GEN-END:variables
}
