/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tfgalejandro;

import java.awt.Color;
import java.util.Random;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author alejandro
 */
public class PanelCompletar extends javax.swing.JPanel {

    private static final String[] WORDS = new String[] {"Leyva","Jesus","Ala","Ver","Bravo","Loco","L"};
    private final Random rnd = new Random();
    private Color textoAleatorioBaseBg;

    /**
     * Creates new form PanelTraduccion
     */
    public PanelCompletar() {
        initComponents();
        // Inicializar con una palabra aleatoria
        setRandomWord();
        // Guardar color base para restaurar después del highlight
        textoAleatorioBaseBg = textoAleatorio.getBackground();
    }

    
    public void addTextoAleatorio(String texto){
        textoAleatorio.setText(textoAleatorio.getText().concat(texto));
    }

    public void setRandomWord() {
        String current = textoAleatorio.getText();
        String pick = WORDS[rnd.nextInt(WORDS.length)];
        // intentar que cambie respecto al actual si es posible
        int tries = 0;
        while (current != null && !current.isEmpty() && pick.equals(current) && tries < 5) {
            pick = WORDS[rnd.nextInt(WORDS.length)];
            tries++;
        }
        textoAleatorio.setText(pick);
        // Al cambiar de palabra limpiamos el texto bajo ella
        textoSignos.setText("");
    }
    
    
    public void addTextoSigno(String texto){
        if (texto == null) return;
        String t = texto.trim();
        if (t.isEmpty()) return;

        // Manejar tokens especiales
        if ("DEL".equalsIgnoreCase(t)) {
            deleteLast();
            return;
        }
        if ("SPACE".equalsIgnoreCase(t)) {
            textoSignos.setText(textoSignos.getText().concat(" "));
            checkIfComplete();
            return;
        }
        if ("NOTHING".equalsIgnoreCase(t)) {
            // No añadir nada
            return;
        }

        // Por defecto, añadir el token tal cual (usualmente una letra)
        textoSignos.setText(textoSignos.getText().concat(t));
        checkIfComplete();
    }
    
    public void setTextoSigno(String texto){
        textoSignos.setText(texto);
    }
    
    public void clearTextoSigno(){
        textoSignos.setText("");
    }
    
    public void deleteLast(){
        String current = textoSignos.getText();
        if (current != null && !current.isEmpty()) {
            textoSignos.setText(current.substring(0, current.length()-1));
        }
    }

    private void checkIfComplete() {
        String target = textoAleatorio.getText();
        String entered = textoSignos.getText();
        if (target == null || entered == null) return;
        if (entered.trim().equalsIgnoreCase(target.trim())) {
            // Resaltar en verde durante 1s y luego cambiar palabra
            textoAleatorio.setBackground(Color.GREEN);
            Timer timer = new Timer(2000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    // Restaurar color y cambiar palabra
                    textoAleatorio.setBackground(textoAleatorioBaseBg);
                    setRandomWord();
                    ((Timer)e.getSource()).stop();
                }
            });
            timer.setRepeats(false);
            timer.start();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelScroll = new javax.swing.JScrollPane();
        textoSignos = new javax.swing.JTextPane();
        panelTextoAleatorio = new javax.swing.JPanel();
        bCambiar = new javax.swing.JButton();
        bLimpiar = new javax.swing.JButton();
        bBorrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoAleatorio = new javax.swing.JTextPane();

        setLayout(new java.awt.BorderLayout());

        textoSignos.setEditable(false);
        textoSignos.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        panelScroll.setViewportView(textoSignos);

        add(panelScroll, java.awt.BorderLayout.CENTER);

        panelTextoAleatorio.setPreferredSize(new java.awt.Dimension(100, 40));
        panelTextoAleatorio.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        bCambiar.setText("Cambiar");
        bCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCambiarActionPerformed(evt);
            }
        });
        panelTextoAleatorio.add(bCambiar);

        bLimpiar.setText("Limpiar");
        bLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarActionPerformed(evt);
            }
        });
        panelTextoAleatorio.add(bLimpiar);

        bBorrar.setText("Borrar");
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });
        panelTextoAleatorio.add(bBorrar);

        add(panelTextoAleatorio, java.awt.BorderLayout.SOUTH);

        textoAleatorio.setEditable(false);
        textoAleatorio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        textoAleatorio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(textoAleatorio);

        add(jScrollPane1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        deleteLast();
    }//GEN-LAST:event_bBorrarActionPerformed

    private void bLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarActionPerformed
        clearTextoSigno();
    }//GEN-LAST:event_bLimpiarActionPerformed

    private void bCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCambiarActionPerformed
        setRandomWord();
    }//GEN-LAST:event_bCambiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bCambiar;
    private javax.swing.JButton bLimpiar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane panelScroll;
    private javax.swing.JPanel panelTextoAleatorio;
    private javax.swing.JTextPane textoAleatorio;
    private javax.swing.JTextPane textoSignos;
    // End of variables declaration//GEN-END:variables
}
