/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tfgalejandro;

import java.lang.reflect.Method;

/**
 *
 * @author jesus
 */
public class PanelTraduccion extends javax.swing.JPanel {

    // Referencia opcional al controlador para delegar acciones
    private Object controller;

    public PanelTraduccion() {
        initComponents();
    }

    /**
     * Permite inyectar el ControllerUI para coordinar acciones desde el Panel.
     */
    public void setController(Object controller) {
        this.controller = controller;
    }

    /**
     * Exponer el componente de texto si el controlador necesita accederlo.
     */
    public javax.swing.JTextPane getTextoComponent() {
        return panelTexto;
    }

    public void addTexto(String texto){
        if (texto == null) return;
        String t = texto.trim();
        if (t.isEmpty()) return;

        // Tokens especiales
        if ("DEL".equalsIgnoreCase(t)) {
            deleteLast();
            return;
        }
        if ("SPACE".equalsIgnoreCase(t)) {
            panelTexto.setText(panelTexto.getText().concat(" "));
            return;
        }
        if ("NOTHING".equalsIgnoreCase(t)) {
            return; // no escribir nada
        }

        // Por defecto añadir tal cual (letra u otro token válido)
        panelTexto.setText(panelTexto.getText().concat(t));
    }
    
    public void deleteLast(){
        String current = panelTexto.getText();
        if (current != null && !current.isEmpty()) {
            panelTexto.setText(current.substring(0, current.length()-1));
        }
    }
    
    public void setTexto(String texto){
        panelTexto.setText(texto);
    }
    
    public void clearTexto(){
        panelTexto.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelScroll = new javax.swing.JScrollPane();
        panelTexto = new javax.swing.JTextPane();
        panelBotones = new javax.swing.JPanel();
        bLimpiar = new javax.swing.JButton();
        bBorrar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        panelTexto.setEditable(false);
        panelTexto.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        panelScroll.setViewportView(panelTexto);

        add(panelScroll, java.awt.BorderLayout.CENTER);

        panelBotones.setPreferredSize(new java.awt.Dimension(100, 40));
        panelBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        bLimpiar.setText("Limpiar");
        bLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarActionPerformed(evt);
            }
        });
        panelBotones.add(bLimpiar);

        bBorrar.setText("Borrar");
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });
        panelBotones.add(bBorrar);

        add(panelBotones, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void bLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarActionPerformed
        // Si hay ControllerUI y ofrece soporte Swing, delegar; si no, fallback local
        if (!tryInvokeController("onTranslationClearAllSwing")) {
            clearTexto();
        }
    }//GEN-LAST:event_bLimpiarActionPerformed

    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        // Si hay ControllerUI y ofrece soporte Swing, delegar; si no, fallback local
        if (!tryInvokeController("onTranslationDeleteLastSwing")) {
            deleteLast();
        }
    }//GEN-LAST:event_bBorrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bLimpiar;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JScrollPane panelScroll;
    private javax.swing.JTextPane panelTexto;
    // End of variables declaration//GEN-END:variables

    // ---------- Helpers ----------
    /**
     * Intenta invocar un método del ControllerUI con firma (JTextComponent).
     * Devuelve true si se invocó correctamente; en caso contrario, false.
     */
    private boolean tryInvokeController(String methodName) {
        if (controller == null) return false;
        try {
            Method m = controller.getClass().getMethod(methodName, javax.swing.text.JTextComponent.class);
            m.invoke(controller, panelTexto);
            return true;
        } catch (NoSuchMethodException e) {
            return false; // El ControllerUI aún no implementa la versión Swing
        } catch (Exception e) {
            // Cualquier otra incidencia: no romper la UI, usar fallback local
            return false;
        }
    }
}
