package tfgalejandro;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import java.awt.BorderLayout;
import java.awt.Dimension;

/**
 *
 * @author alejandro
 */
public class PanelCamara extends javax.swing.JPanel {
    private Webcam myCamera;
    private WebcamPanel myVisual;
    
    /**
     * Creates new form PanelCamara
     */
    public PanelCamara() {
        initComponents();
        startWebCam();
    }


    public final void startWebCam() {
        myCamera = Webcam.getDefault();        
        if (myCamera != null) {          
            //Activamos la máxima resolución posible
            Dimension resoluciones[] = myCamera.getViewSizes();
            Dimension maxRes = resoluciones[resoluciones.length-1];
            myCamera.setViewSize(maxRes);            
            //Creamos el panel de visualización
            myVisual = new WebcamPanel(myCamera,maxRes,true);
            if (myVisual != null) {                    
                myVisual.setFitArea(false);                
                this.add(myVisual, BorderLayout.CENTER);               
                this.setSize(maxRes); 
                this.repaint();
            }
        }
    }
     
    /**
     * Devuelve la cámara asociada a este panel
     * @return la cámara del panel.
     */
    public Webcam getCamera() {
        return myCamera;
    }
      
    /**
     * Devuelve la resolución de la cámara activa.
     * @return la resolución de la cámara activa, null si no la hay.
     */
    public Dimension getResolucion(){
        Dimension dim = null;
        if (myCamera != null) {
            myCamera.getViewSize();
        }
        return dim;
    }
    
     /**
     *  Cierra la webcam
     */
    public void close(){
        if (myCamera != null) {
            myCamera.close();
            // Quitamos areas visual, control, etc.
            this.removeAll();
            myCamera = null;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
